### PR TITLE
Update AWS SDK to v3

### PR DESCRIPTION
**Pull request by pedromdev**
Solves #4

### CODE REVIEW

**Comment by KerryRitter** [comment]
Amazing - I will take a look early this week. Thank you for the contribution!

**Comment by KerryRitter** [comment]
This looks good! Going to run a couple more tests this week and we can merge and publish this weekend if that sounds good to you. Thank you so much for the contribution.

**Comment by pedromdev** [comment]
That's great @KerryRitter ! I'm going deeper into the documentation to see the changes in the options of each service. I noted that each service has its options and I don't know if it's possible change it in runtime (like method call). May I create a new PR with new updates.

**Comment by KerryRitter** [comment]
That's actually my concern that I want to dig deeper into. In V2, each
service had (if not exact, essentially) the same service options. I can't
tell if that's the same case with V3, in which case the default service
options approach might not work out.

**Comment by jarcodallo** [comment]
Hi guys @pedromdev @KerryRitter, any news about this? I'm serious thinking in doing a `nestjs-aws-sdk-v3` module, but I don't want to build a new whole module if we can add it here.

**Comment by KerryRitter** [comment]
Rejecting for now because we have lots of conflicts (because of our fault, sorry). If someone has time to fix this up and do some proving and documentation for this, I am happy to accept a PR to support v3. 

It would be ideal to support either v2 OR v3.

**Comment by troywweber7** [comment]
What's the verdict on this? V2 is supposed to be deprecated this year, 2023.

**Pull request closed without merging**
